version: '3.8'

services:
  redis-master:
    image: redis:7
    container_name: redis-master
    ports:
      - "6380:6380"
    networks:
      - redis-net

  redis-slave-1:
    image: redis:7
    container_name: redis-slave-1
    depends_on:
      - redis-master
    command: ["redis-server", "--replicaof", "redis-master", "6379"]
    networks:
      - redis-net

  redis-slave-2:
    image: redis:7
    container_name: redis-slave-2
    depends_on:
      - redis-master
    command: ["redis-server", "--replicaof", "redis-master", "6379"]
    networks:
      - redis-net

networks:
  redis-net:
