version: '3'
services:
  coordinador:
    image: postgres
    container_name: coordinador
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  servidor1:
    image: postgres
    container_name: servidor1
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  servidor2:
    image: postgres
    container_name: servidor2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
